import type { NextPage } from "next";
import Head from "next/head";
import TasksList from "../interfaces/tasks-list.interface";
import TasksListComponent from "../components/tasks-list.component";
import { DragDropContext, DropResult } from "react-beautiful-dnd";
import React, { useEffect, useRef, useState } from "react";
import Task from "../interfaces/task.interface";
import BaseModalComponent from "../components/base-modal.component";
import { tasksService } from "./_app";

type Props = {
  storedTasksLists: TasksList[];
};

type TaskContextValue = {
  onChangeTask?: (task: Task) => Promise<void>;
  onDeleteTask?: (task: Task) => Promise<void>;
};

export const TaskContext = React.createContext<TaskContextValue>({});

const Home: NextPage<Props> = ({ storedTasksLists }) => {
  const [ready, setReady] = useState(false);
  const [tasksLists, setTasksLists] = useState(storedTasksLists);

  const taskRef = useRef<Task>();

  useEffect(() => {
    if (typeof window === "object") {
      setReady(true);
    }
  }, []);

  const onDragEnd = async (result: DropResult): Promise<void> => {
    if (!result.source || !result.destination) {
      return;
    }

    const originList = tasksLists.find(
      (list) => list.id === result.source.droppableId
    );
    if (!originList) {
      return;
    }

    const destinationList = tasksLists.find(
      (list) => list.id === result.destination?.droppableId
    );
    if (!destinationList) {
      return;
    }

    const draggedTask = originList.tasks[result.source.index];
    if (!draggedTask) {
      return;
    }

    draggedTask.tasksListId = destinationList.id;
    originList.tasks.splice(result.source.index, 1);
    destinationList.tasks.splice(result.destination.index, 0, draggedTask);

    originList.tasks.forEach((task, index) => {
      task.index = index;
    });

    destinationList.tasks.forEach((task, index) => {
      task.index = index;
    });

    const uptatedTasks = [...originList.tasks, ...destinationList.tasks];

    try {
      await tasksService.updateTasks(uptatedTasks);
    } catch (error) {
      console.error(error);
    }
  };

  const onChangeTask = async (taskToUpdate: Task): Promise<void> => {
    const tasksList = tasksLists.find(
      (list) => list.id === taskToUpdate.tasksListId
    );
    if (!tasksList) return;

    const originalTask = tasksList.tasks.find(
      (task) => task.id === taskToUpdate.id
    );
    if (originalTask == null) return;

    originalTask.deployed = taskToUpdate.deployed;

    await tasksService.updateTasks([originalTask]);
  };

  const onDeleteTask = async (task: Task): Promise<void> => {
    taskRef.current = task;
  };

  const handleDeleteDialog = async (choose: boolean) => {
    if (!choose) return;
    if (!taskRef.current) return;

    const newTasksLists = [...tasksLists];

    const originalList = newTasksLists.find(
      (list) => list.id === taskRef.current?.tasksListId
    );
    if (!originalList) return;

    const originalTask = originalList.tasks.find(
      (task) => task.id === taskRef.current?.id
    );
    if (originalTask) {
      originalList.tasks = originalList.tasks.filter(
        (task) => task.id !== originalTask.id
      );
      setTasksLists(newTasksLists);
      await tasksService.deleteTask(originalTask);
    }
  };

  return (
    <div className="container">
      <Head>
        <title>Tasks App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="my-5">Tasks App!</h1>

        <div className="row">
          {ready && (
            <DragDropContext onDragEnd={onDragEnd}>
              {tasksLists.map((tasksList) => (
                <TaskContext.Provider
                  key={tasksList.id}
                  value={{ onChangeTask, onDeleteTask }}
                >
                  <TasksListComponent tasksList={tasksList} />
                </TaskContext.Provider>
              ))}
            </DragDropContext>
          )}
        </div>
      </main>

      <BaseModalComponent
        id="DeleteConfirmation"
        title="Alert"
        body="Are you sure you want to delete this task?"
        dialogResult={handleDeleteDialog}
      />
    </div>
  );
};

export async function getServerSideProps(): Promise<{ props: Props }> {
  const data = await tasksService.getTasksLists();
  return { props: { storedTasksLists: data } };
}

export default Home;
