import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import TasksList from "../interfaces/tasks-list.interface";
import TasksListComponent from "../components/tasks-list.component";

const Home: NextPage<{ tasksLists: TasksList[] }> = ({ tasksLists }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tasks App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Create new <a href="https://nextjs.org">task!</a>
        </h1>

        <div className={styles.grid}>
          {tasksLists.map((tasksList) => {
            return (
              <div key={tasksList.id} className={styles.card}>
                <TasksListComponent tasksList={tasksList} />
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/tasks-list`);
  const data = await res.json();
  return { props: { tasksLists: data } };
}

export default Home;
